version: '3'


tasks:
  
  default:
    desc: Default task
    cmds:
      - task example
  
  example:
    desc: Runs the main example
    cmds:
      - go run main.go

  test:
    desc: Runs the test cases
    cmds:
      - go test -v ./...

  
