version: '3'

env:
  PATH_PREFIX: $HOME/.local/go/bin:$HOME/go/bin:$PATH

tasks:
  test:
    desc: Runs the test cases including static tests
    cmds:
      - PATH="{{.PATH_PREFIX}}" staticcheck ./...
      - PATH="{{.PATH_PREFIX}}" golangci-lint run ./...
      - go vet ./...
      - go test -v -race ./...


  
